version: '3.8'  # Specify the version of Docker Compose

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:v2.2.1
    restart: always
    container_name: traefik
    ports:
      - '80:80'  # HTTP
      - '443:443'  # HTTPS
    command:
      - --api.insecure=false  # Disable insecure API
      - --api.dashboard=true  # Enable the dashboard
      - --api.debug=true  # Enable debug endpoints
      - --log.level=DEBUG  # Set log level
      - --providers.docker=true  # Enable Docker provider
      - --providers.docker.exposedbydefault=false  # Don't expose all containers
      - --entrypoints.web.address=:80  # HTTP entrypoint
      - --entrypoints.web-secured.address=:443  # HTTPS entrypoint
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true  # Enable TLS-ALPN-01
      - --certificatesresolvers.mytlschallenge.acme.email=${ACME_EMAIL}  # Email for certs
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json  # Storage for certs
    volumes:
      - ./conf/traefik/letsencrypt:/letsencrypt  # Volume for certs
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket
    labels:
      traefik.enable: true  # Enable Traefik for this container
      traefik.http.routers.http_catchall.rule: hostregexp(`{host:.*}`)
      traefik.http.routers.http_catchall.entryPoints: web
      traefik.http.routers.http_catchall.middlewares: redirect_https  # Redirect to HTTPS
      traefik.http.routers.traefik.rule: Host(`traefik.${APP_DOMAIN}`)  # Dashboard domain
      traefik.http.routers.traefik.entryPoints: web-secured
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.certresolver: mytlschallenge
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.redirect_https.redirectscheme.scheme: https  # HTTPS redirection middleware

  ################################################
  ####     v2ray server container      #####
  ##############################################
  v2ray:
    image: alphacodinghub/v2ray-nginx
    container_name: v2ray
    restart: always
    environment:
      LISTENING_PORT: ${LISTENING_PORT:-3003}
      CLIENT_ID: ${CLIENT_ID:-2e5762cc-20d2-42b1-b0ad-cbe55dc5fa35}
      CLIENT_ALTERID: ${CLIENT_ALTERID:-64}
      CLIENT_WSPATH: ${CLIENT_WSPATH:-/allproducts}
    volumes:
      - ./conf/html:/var/www/html
    labels:
      traefik.enable: true  # Enable Traefik for this container
      traefik.http.routers.v2ray.rule: Host(`${APP_NAME}.${APP_DOMAIN}`)  # Domain for the v2ray service
      traefik.http.routers.v2ray.entrypoints: web-secured  # HTTPS entrypoint
      traefik.http.routers.v2ray.tls.certresolver: mytlschallenge  # Cert resolver for HTTPS
